name: Build-Linux-Precompiled-Binaries

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-precompiled-bin-x86_64:
    runs-on: kuzu-self-hosted-linux-building
    steps:
      - uses: actions/checkout@v3

      - name: Install networkx
        run: /opt/python/cp310-cp310/bin/python -m pip install networkx --user

      - name: Build precompiled binaries
        run: |
          source /opt/rh/devtoolset-11/enable
          /opt/python/cp310-cp310/bin/python build.py
        working-directory: ./scripts/pre-compiled-bins/

      - uses: actions/upload-artifact@v3
        with:
          name: libkuzu-linux-x86_64
          path: |
            ./scripts/pre-compiled-bins/kuzu.h
            ./scripts/pre-compiled-bins/kuzu.hpp
            ./scripts/pre-compiled-bins/libkuzu.so

      - uses: actions/upload-artifact@v3
        with:
          name: kuzu_cli-linux-x86_64
          path: ./scripts/pre-compiled-bins/kuzu

  build-precompiled-bin-aarch64:
    runs-on: kuzu-self-hosted-linux-building-aarch64
    steps:
      - uses: actions/checkout@v3

      - name: Install networkx
        run: /opt/python/cp310-cp310/bin/python -m pip install networkx --user

      - name: Build precompiled binaries
        run: /opt/python/cp310-cp310/bin/python build.py
        working-directory: ./scripts/pre-compiled-bins/

      - uses: actions/upload-artifact@v3
        with:
          name: libkuzu-linux-aarch64
          path: |
            ./scripts/pre-compiled-bins/kuzu.h
            ./scripts/pre-compiled-bins/kuzu.hpp
            ./scripts/pre-compiled-bins/libkuzu.so

      - uses: actions/upload-artifact@v3
        with:
          name: kuzu_cli-linux-aarch64
          path: ./scripts/pre-compiled-bins/kuzu
