name: Build-Linux-Precompiled-Binaries

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "Version of output package"
        required: true
        default: "0.0.1"

env:
  PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}

jobs:
  build-precompiled-bin:
    runs-on: kuzu-self-hosted-linux-building
    steps:
      - uses: actions/checkout@v3

      - name: Install networkx
        run: /opt/python/cp310-cp310/bin/python -m pip install networkx --user

      - name: Build precompiled binaries
        run: /opt/python/cp310-cp310/bin/python build.py
        working-directory: ./scripts/pre-compiled-bins/

      - uses: actions/upload-artifact@v3
        with:
          name: kuzu-${{ github.event.inputs.packageVersion }}-linux-x86_64
          path: |
            ./scripts/pre-compiled-bins/kuzu
            ./scripts/pre-compiled-bins/kuzu.h
            ./scripts/pre-compiled-bins/libkuzu.so

      - name: Clean up
        run: rm -rf ./scripts/pre-compiled-bins/kuzu ./scripts/pre-compiled-bins/headers ./scripts/pre-compiled-bins/libkuzu.so /scripts/pre-compiled-bins/kuzu.h
