name: Build Linux Java Lib
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-linux-java-x86_64:
    runs-on: kuzu-self-hosted-linux-building-x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          /opt/python/cp310-cp310/bin/python -m pip install packaging
          /opt/python/cp310-cp310/bin/python update-nightly-build-version.py
        working-directory: scripts

      - name: Build Java lib for Linux
        run: |
          make java NUM_THREADS=$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-linux-x86_64
          path: tools/java_api/build/libkuzu_java_native*

  build-linux-java-aarch64:
    runs-on: kuzu-self-hosted-linux-building-aarch64
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          /opt/python/cp310-cp310/bin/python -m pip install packaging
          /opt/python/cp310-cp310/bin/python update-nightly-build-version.py
        working-directory: scripts

      - name: Build Java lib for Linux
        run: make java NUM_THREADS=$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-linux-aarch64
          path: tools/java_api/build/libkuzu_java_native*

  build-linux-java-armv8a:
    runs-on: kuzu-self-hosted-testing
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          python3 -m pip install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build Java lib for Linux
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DBUILD_JAVA=TRUE -DBUILD_SHELL=FALSE ..
          make -j$(nproc)
    
      - name: Rename artifact
        run: |
          mv tools/java_api/build/libkuzu_java_native.so_linux_arm64 tools/java_api/build/libkuzu_java_native.so_android_arm64
      
      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-android-armv8a
          path: tools/java_api/build/libkuzu_java_native*
