name: Build-Windows-Precompiled-Binaries

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-precompiled-bin:
    runs-on: self-hosted-windows
    steps:
      - uses: actions/checkout@v3

      - name: Build precompiled binaries
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          make LTO=1 NUM_THREADS=%NUMBER_OF_PROCESSORS%
          make install

      - name: Collect artifacts
        shell: cmd
        run: |
          move install\include\kuzu.h
          move install\include\kuzu.hpp
          move install\bin\kuzu_shared.dll
          move install\lib\kuzu_shared.lib
          move install\bin\kuzu_shell.exe kuzu.exe


      - uses: actions/upload-artifact@v3
        with:
          name: libkuzu-windows-x86_64
          path: |
            kuzu.h
            kuzu.hpp
            kuzu_shared.dll
            kuzu_shared.lib

      - uses: actions/upload-artifact@v3
        with:
          name: kuzu_cli-windows-x86_64
          path: kuzu.exe
